name: build
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 * * 6' # weekly check that it still works

env:
  BROWSER_STATE: Headless

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Download repository
        uses: actions/checkout@v5

      # https://github.com/actions/setup-java
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Test with Maven
        run: mvn -Dwebdriver.chrome.logfile=${{ github.workspace }}/chromedriver.log -Dwebdriver.chrome.verboseLogging=true test

      - name: Show logs
        run: |
          cat ${{ github.workspace }}/chromedriver.log
        shell: bash
